import React from "react";
import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-900 text-gray-300 font-sans p-8">
      <div className="max-w-3xl mx-auto bg-gray-800 p-8 rounded-xl shadow-lg border border-gray-700">
        <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
        <p className="mb-4 text-sm text-gray-400">Last Updated: November 29, 2025</p>

        <section className="mb-6">
          <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing and using AI Secretary, you agree to comply with and be bound by these Terms of Service. 
            If you do not agree to these terms, please do not use our service.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
          <p>
            AI Secretary is a personal scheduling assistant that uses Artificial Intelligence to organize your tasks and appointments. 
            The service is provided &quot;as is&quot; and is intended for personal productivity use.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold text-white mb-3">3. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>You are responsible for maintaining the confidentiality of your Google account credentials.</li>
            <li>You agree not to use the service for any illegal or unauthorized purpose.</li>
            <li>You are responsible for verifying the accuracy of any schedule generated by the AI before relying on it.</li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold text-white mb-3">4. Limitation of Liability</h2>
          <p>
            AI Secretary and its developers shall not be liable for any direct, indirect, incidental, or consequential damages 
            resulting from the use or inability to use the service, including but not limited to missed appointments, 
            scheduling conflicts, or data loss.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold text-white mb-3">5. API Usage</h2>
          <p>
            Our service utilizes the Google Gemini API. Your use of the service is also subject to Google&apos;s 
            <a href="https://policies.google.com/terms" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline ml-1">
              Terms of Service
            </a>.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-xl font-semibold text-white mb-3">6. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of any changes.
          </p>
        </section>

        <div className="mt-8 pt-6 border-t border-gray-700">
          <Link href="/" className="text-blue-400 hover:text-blue-300 hover:underline">
            &larr; Back to App
          </Link>
        </div>
      </div>
    </div>
  );
}